// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQTDWoCXRVE0WfEu7UVoHtTXolY4A1kE',
    appId: '1:63082519291:web:d61e75e17911b4f6fe2e5e',
    messagingSenderId: '63082519291',
    projectId: 'abilifyapp',
    authDomain: 'abilifyapp.firebaseapp.com',
    storageBucket: 'abilifyapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFKiM_grpLHSZNBr5s83Dtq3czcXWmCg',
    appId: '1:63082519291:android:4abf0e19dbbb3e4cfe2e5e',
    messagingSenderId: '63082519291',
    projectId: 'abilifyapp',
    storageBucket: 'abilifyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_crj1hPJbd1rT2D4mZfzy7T2OH-jQfE',
    appId: '1:63082519291:ios:b8135bba6baf9293fe2e5e',
    messagingSenderId: '63082519291',
    projectId: 'abilifyapp',
    storageBucket: 'abilifyapp.firebasestorage.app',
    iosBundleId: 'com.example.abilify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_crj1hPJbd1rT2D4mZfzy7T2OH-jQfE',
    appId: '1:63082519291:ios:b8135bba6baf9293fe2e5e',
    messagingSenderId: '63082519291',
    projectId: 'abilifyapp',
    storageBucket: 'abilifyapp.firebasestorage.app',
    iosBundleId: 'com.example.abilify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzQTDWoCXRVE0WfEu7UVoHtTXolY4A1kE',
    appId: '1:63082519291:web:20e1810ea33bf443fe2e5e',
    messagingSenderId: '63082519291',
    projectId: 'abilifyapp',
    authDomain: 'abilifyapp.firebaseapp.com',
    storageBucket: 'abilifyapp.firebasestorage.app',
  );

}